config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
              :controllers => { :registrations => "registrations" }

  root 'secret_codes#index'

  resources :secret_codes do
    collection do
      get 'generate_codes'
    end
  end
  

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.role.try(:name) == 'admin'
      can :manage, :all
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/role.rb
class Role < ActiveRecord::Base
	has_many :users
end

app/models/secret_code.rb
class SecretCode < ActiveRecord::Base

	 belongs_to :user, :foreign_key => 'user_id'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_one :secret_code
  belongs_to :role
 
  def self.update_secret_code(secret_code,user_id)
  	SecretCode.create(secret_code: secret_code, user_id: user_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user!

 # 	def after_sign_in_path_for(resource)
 # #    root_path
 #  	if current_user.role.try(:name) != 'admin'
	# 		#render 'welcome/welcome'
	# 		redirect_to root_path
 #    end
	# end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
    
  def new
  	super
  end

	def create
		super
		if @user.save
			User.update_secret_code(params[:secret_code],@user.id)
		end
	end

end

app/controllers/secret_codes_controller.rb
class SecretCodesController < ApplicationController

	def index
		if current_user.role.try(:name) == 'admin'
			@secret_codes = SecretCode.all.paginate(:page => params[:page], :per_page => 15)
		else
			render 'welcome/welcome'
		end
	end

	def generate_codes
		if can? :create, SecretCode 
			params["code_num"].to_i.times.each do 
			 SecretCode.create(secret_code: SecureRandom.hex(2))
		  end
			redirect_to secret_codes_path
		else
			flash[:error] = "You are not authorised user for accessing this page"
			redirect_to secret_codes_path
		end
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper

	def secret_codes
		secret_codes = SecretCode.where(user_id: nil)
	end
	
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Grouptable</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'jquery.validate.min', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
 	<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <p class="navbar-text pull-right">
				<% if user_signed_in? %>
  				Logged in as <strong><%= current_user.email %></strong>
  				|
  				<%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
				<% else %>
  				<%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  				<%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
				<% end %>
      </div>
    </div>
  </nav>
	<div class="container">
	    <div class="row">
	      <div class="col-lg-12 text-center">
	        <%= yield %>
	      </div>
	    </div>
	  </div>
</body>
</html>

<style>
  body {
      padding-top: 70px;
      /* Required padding for .navbar-fixed-top. Remove if using .navbar-static-top. Change if height of navigation changes. */
  }
</style>

app/views/secret_codes/index.hrml.erb
dsffsdll

app/views/secret_codes/index.html.erb
<div class="secret-table"> 
  <h2>Secret Codes List</h2>
  <% if can? :generate_codes, @secret_codes %>
    <div class="random-gen">
      <%= form_tag generate_codes_secret_codes_path, :method => "get" do  %>
        <%= select_tag "code_num", options_for_select([['1'], ['10'], ['20'],['50'],['100']], params[:code_num] ) , :class => "form-control"%>
        <%= submit_tag "gen", :class => "generation btn btn-info"%>
      <% end %>
    </div>
  <% end %>
  <table class="table">
    <thead>
      <tr>
        <th class="table-heading">Sl.No</th>
        <th class="table-heading">Secret Code</th>
        <th class="table-heading">Email Address</th>
      </tr>
    </thead>
    <tbody>
      <% @secret_codes.each do |code| %>
      <tr class="success">
        <td>1</td>
        <td><%= code.secret_code %></td>
        <td><%= code.user.email unless code.user.nil?%></td>
      </tr>
      <% end %>
    </tbody>
  </table>
  <%= will_paginate @secret_codes %>
</div>

app/views/welcome/welcome.html.erb
<div class="welcome-img">
	<img src="../../assets/welcome.jpg" class="img-responsive" alt="Responsive image"/>
</div>